### ISSUE TITLE
Add info about the reviewing model

### ISSUE THREAD

**Issue by carlosmalt** [acm-rep/2023#3]
Dan Katz pointed out that we might want to add info about the reviewing model to the CFP and CFT (e.g. double-blind, single-blind).

**Comment by gflofst** [comment]
I just had a second question about this. In spite of the pain, I would vote for double anonymized if we are going to hide anything. Otherwise, I am actually quite happy with fully open. We don't have a control for using the double anonymized in computer science. Anecdotally, it seems to be neutral to maybe a tiny benefit. For places where we want discussion, I think open can work better. What does others think?

**Comment by carlosmalt** [comment]
Double-blind paper reviews in CS conferences are becoming pretty standard. On the other hand, artifact evaluation requires much more interaction and people have successfully tried double-open (e.g. SC20) and single-blind (e.g. SC21, with @TanuMalik as AD/AE co-chair).  But we decided trying to not separate paper review and artifact evaluation. Double-blind might be too difficult for artifact evaluation.

My opinion is that double-open exposes  junior members of the PC to an extent that they might not even realize. Junior members are in a career stage where a disgruntled author can inflict serious damage on their careers, often in ways they might never know nor be able to defend against. And I think the likelihood of some authors being disgruntled is probably higher in a conference with little precedence.

So I strongly recommend single-blind.

**Comment by carlosmalt** [comment]
Also, individual reviewers are always free to sign their review with their name. Single-blind (and double-blind) gives reviewers that choice.

**Comment by TanuMalik** [comment]
I think double anonymized is needed where there is significant competition and vested interests. We are trying to build a community, and the idea is to be in general helpful. So I would like to go with single-blind, but in case of medium reviews someone will have to champion the paper, or we can ask senior member opinion.
